export const EMAIL_MIN_LENGTH = 3
export const EMAIL_MAX_LENGTH = 254
export const PASSWORD_MIN_LENGTH = 8
export const PASSWORD_MAX_LENGTH = 255

export const PROJECT_NAME_MIN_LENGTH = 3
export const PROJECT_NAME_MAX_LENGTH = 255
export const PROJECT_DESCRIPTION_MIN_LENGTH = 3
export const PROJECT_DESCRIPTION_MAX_LENGTH = 8000
